version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:  # Volumen para persistir datos